# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20171020_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
